namespace TaxServiceAdaptor.DTO {
    public enum CommandType {
        PRIVATE_KEY_APPLICATION__R_R_01,
        TAX_INFORMATION_APPLICATION__R_R_02,
        INITIALIZATION_SUCCESS_NOTIFICATION__R_R_03,
        INVOICE_APPLICATION__INVOICE_APP_R,
        INVOICE_UPLOAD__INVOICE_REPORT_R,
        TIME_SYNCHRONIZATION__SYS_TIME_R,
        HEART_BEAT_MONITORING__MONITOR_R,
        REACTIVATION__RECOVER_R
    }
}